CREATE TABLE countries (
  code CHAR(2) PRIMARY KEY,
  name VARCHAR(255),
  continentcode CHAR(2)
);

CREATE INDEX idx_code ON countries(code);

INSERT INTO countries (code, name, continentcode) VALUES ('AD', 'Andorra', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('AE', 'United Arab Emirates', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('AF', 'Afghanistan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('AG', 'Antigua and Barbuda', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('AI', 'Anguilla', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('AL', 'Albania', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('AM', 'Armenia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('AN', 'Netherlands Antilles', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('AO', 'Angola', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('AQ', 'Antarctica', 'AN');
INSERT INTO countries (code, name, continentcode) VALUES ('AR', 'Argentina', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('AS', 'American Samoa', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('AT', 'Austria', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('AU', 'Australia', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('AW', 'Aruba', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('AX', 'Åland', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('AZ', 'Azerbaijan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('BA', 'Bosnia and Herzegovina', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('BB', 'Barbados', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('BD', 'Bangladesh', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('BE', 'Belgium', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('BF', 'Burkina Faso', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('BG', 'Bulgaria', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('BH', 'Bahrain', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('BI', 'Burundi', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('BJ', 'Benin', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('BL', 'Saint Barthélemy', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('BM', 'Bermuda', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('BN', 'Brunei Darussalam', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('BO', 'Bolivia', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('BR', 'Brazil', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('BS', 'Bahamas', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('BT', 'Bhutan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('BV', 'Bouvet Island', 'AN');
INSERT INTO countries (code, name, continentcode) VALUES ('BW', 'Botswana', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('BY', 'Belarus', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('BZ', 'Belize', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('CA', 'Canada', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('CC', 'Cocos (Keeling) Islands', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('CD', 'Congo (Kinshasa)', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('CF', 'Central African Republic', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('CG', 'Congo (Brazzaville)', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('CH', 'Switzerland', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('CI', 'Côte dIvoire', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('CK', 'Cook Islands', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('CL', 'Chile', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('CM', 'Cameroon', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('CN', 'China', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('CO', 'Colombia', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('CR', 'Costa Rica', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('CU', 'Cuba', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('CV', 'Cape Verde', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('CX', 'Christmas Island', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('CY', 'Cyprus', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('CZ', 'Czech Republic', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('DE', 'Germany', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('DJ', 'Djibouti', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('DK', 'Denmark', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('DM', 'Dominica', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('DO', 'Dominican Republic', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('DZ', 'Algeria', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('EC', 'Ecuador', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('EE', 'Estonia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('EG', 'Egypt', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('EH', 'Western Sahara', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('ER', 'Eritrea', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('ES', 'Spain', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('ET', 'Ethiopia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('FI', 'Finland', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('FJ', 'Fiji', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('FK', 'Falkland Islands', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('FM', 'Micronesia', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('FO', 'Faroe Islands', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('FR', 'France', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('GA', 'Gabon', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('GB', 'United Kingdom', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('GD', 'Grenada', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('GE', 'Georgia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('GF', 'French Guiana', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('GG', 'Guernsey', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('GH', 'Ghana', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('GI', 'Gibraltar', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('GL', 'Greenland', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('GM', 'Gambia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('GN', 'Guinea', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('GP', 'Guadeloupe', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('GQ', 'Equatorial Guinea', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('GR', 'Greece', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('GS', 'South Georgia and South Sandwich Islands', 'AN');
INSERT INTO countries (code, name, continentcode) VALUES ('GT', 'Guatemala', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('GU', 'Guam', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('GW', 'Guinea-Bissau', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('GY', 'Guyana', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('HK', 'Hong Kong', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('HM', 'Heard and McDonald Islands', 'AN');
INSERT INTO countries (code, name, continentcode) VALUES ('HN', 'Honduras', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('HR', 'Croatia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('HT', 'Haiti', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('HU', 'Hungary', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('ID', 'Indonesia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('IE', 'Ireland', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('IL', 'Israel', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('IM', 'Isle of Man', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('IN', 'India', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('IO', 'British Indian Ocean Territory', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('IQ', 'Iraq', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('IR', 'Iran', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('IS', 'Iceland', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('IT', 'Italy', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('JE', 'Jersey', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('JM', 'Jamaica', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('JO', 'Jordan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('JP', 'Japan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('KE', 'Kenya', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('KG', 'Kyrgyzstan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('KH', 'Cambodia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('KI', 'Kiribati', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('KM', 'Comoros', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('KN', 'Saint Kitts and Nevis', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('KP', 'Korea, North', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('KR', 'Korea, South', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('KW', 'Kuwait', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('KY', 'Cayman Islands', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('KZ', 'Kazakhstan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('LA', 'Laos', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('LB', 'Lebanon', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('LC', 'Saint Lucia', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('LI', 'Liechtenstein', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('LK', 'Sri Lanka', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('LR', 'Liberia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('LS', 'Lesotho', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('LT', 'Lithuania', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('LU', 'Luxembourg', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('LV', 'Latvia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('LY', 'Libya', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MA', 'Morocco', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MC', 'Monaco', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('MD', 'Moldova', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('ME', 'Montenegro', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('MF', 'Saint Martin (French part)', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('MG', 'Madagascar', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MH', 'Marshall Islands', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('MK', 'Macedonia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('ML', 'Mali', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MM', 'Myanmar', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('MN', 'Mongolia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('MO', 'Macau', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('MP', 'Northern Mariana Islands', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('MQ', 'Martinique', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('MR', 'Mauritania', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MS', 'Montserrat', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('MT', 'Malta', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('MU', 'Mauritius', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MV', 'Maldives', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('MW', 'Malawi', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('MX', 'Mexico', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('MY', 'Malaysia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('MZ', 'Mozambique', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('NA', 'Namibia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('NC', 'New Caledonia', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('NE', 'Niger', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('NF', 'Norfolk Island', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('NG', 'Nigeria', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('NI', 'Nicaragua', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('NL', 'Netherlands', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('NO', 'Norway', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('NP', 'Nepal', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('NR', 'Nauru', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('NU', 'Niue', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('NZ', 'New Zealand', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('OM', 'Oman', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('PA', 'Panama', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('PE', 'Peru', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('PF', 'French Polynesia', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('PG', 'Papua New Guinea', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('PH', 'Philippines', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('PK', 'Pakistan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('PL', 'Poland', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('PM', 'Saint Pierre and Miquelon', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('PN', 'Pitcairn', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('PR', 'Puerto Rico', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('PS', 'Palestine', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('PT', 'Portugal', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('PW', 'Palau', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('PY', 'Paraguay', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('QA', 'Qatar', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('RE', 'Reunion', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('RO', 'Romania', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('RS', 'Serbia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('RU', 'Russian Federation', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('RW', 'Rwanda', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SA', 'Saudi Arabia', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('SB', 'Solomon Islands', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('SC', 'Seychelles', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SD', 'Sudan', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SE', 'Sweden', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('SG', 'Singapore', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('SH', 'Saint Helena', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SI', 'Slovenia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('SJ', 'Svalbard and Jan Mayen Islands', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('SK', 'Slovakia', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('SL', 'Sierra Leone', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SM', 'San Marino', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('SN', 'Senegal', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SO', 'Somalia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SR', 'Suriname', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('ST', 'Sao Tome and Principe', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('SV', 'El Salvador', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('SY', 'Syria', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('SZ', 'Swaziland', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('TC', 'Turks and Caicos Islands', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('TD', 'Chad', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('TF', 'French Southern Lands', 'AN');
INSERT INTO countries (code, name, continentcode) VALUES ('TG', 'Togo', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('TH', 'Thailand', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('TJ', 'Tajikistan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('TK', 'Tokelau', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('TL', 'Timor-Leste', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('TM', 'Turkmenistan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('TN', 'Tunisia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('TO', 'Tonga', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('TR', 'Turkey', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('TT', 'Trinidad and Tobago', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('TV', 'Tuvalu', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('TW', 'Taiwan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('TZ', 'Tanzania', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('UA', 'Ukraine', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('UG', 'Uganda', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('UM', 'United States Minor Outlying Islands', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('US', 'United States of America', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('UY', 'Uruguay', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('UZ', 'Uzbekistan', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('VA', 'Vatican City', 'EU');
INSERT INTO countries (code, name, continentcode) VALUES ('VC', 'Saint Vincent and the Grenadines', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('VE', 'Venezuela', 'SA');
INSERT INTO countries (code, name, continentcode) VALUES ('VG', 'Virgin Islands, British', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('VI', 'Virgin Islands, U.S.', 'NA');
INSERT INTO countries (code, name, continentcode) VALUES ('VN', 'Vietnam', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('VU', 'Vanuatu', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('WF', 'Wallis and Futuna Islands', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('WS', 'Samoa', 'OC');
INSERT INTO countries (code, name, continentcode) VALUES ('YE', 'Yemen', 'AS');
INSERT INTO countries (code, name, continentcode) VALUES ('YT', 'Mayotte', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('ZA', 'South Africa', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('ZM', 'Zambia', 'AF');
INSERT INTO countries (code, name, continentcode) VALUES ('ZW', 'Zimbabwe', 'AF');